import { describe, expect, it, vi } from "vitest";

const { fetchMarketSeriesBatch, auditWithLLM, sendTelegramMessage, recordTelegramDelivery, insert, db } = vi.hoisted(() => {
  const fetchMarketSeriesBatch = vi.fn(async () => { throw new Error("Twelve Data quota exhausted"); });
  const auditWithLLM = vi.fn();
  const sendTelegramMessage = vi.fn();
  const recordTelegramDelivery = vi.fn();
  const insert = vi.fn();
  const select = vi.fn(() => ({
    from: vi.fn(() => ({
      where: vi.fn(async () => []),
    })),
  }));
  const db = { select, insert, update: vi.fn() };
  return { fetchMarketSeriesBatch, auditWithLLM, sendTelegramMessage, recordTelegramDelivery, insert, db };
});

vi.mock("./db", () => ({
  getDb: vi.fn(async () => db),
  listStrategyRules: vi.fn(async () => [{ id: 1, title: "Rules", content: "Use confirmation." }]),
  getAllRulesText: vi.fn(async () => "Use confirmation."),
  getRelevantRulesText: vi.fn(async () => "## Rules\nUse confirmation."),
  createStrategyRule: vi.fn(),
  recordTelegramDelivery,
}));

vi.mock("./integrations", () => ({
  fetchMarketSeriesBatch,
  fetchMarketSnapshot: vi.fn(),
  fetchStrategyRulesFromSupabase: vi.fn(async () => []),
  forensicAnalysis: vi.fn(),
  auditWithLLM,
  formatApprovedTelegramMessage: vi.fn(() => "approved"),
  formatAuditResult: vi.fn(() => "audit"),
  mirrorToSupabase: vi.fn(),
  sendTelegramMessage,
}));

import { scanUser, shouldNotifyScannerSignal } from "./scanner";

const series = (symbol: string, interval: "15min" | "1h") => ({
  symbol,
  interval,
  values: [{ close: "1" }, { close: "2" }, { close: "3" }],
  close: 3,
  trend: "UP" as const,
  fetchedAt: new Date().toISOString(),
});

describe("scanner approval gate", () => {
  it("allows only approved outcomes to reach the notification branch", () => {
    expect(shouldNotifyScannerSignal("APPROVED")).toBe(true);
    expect(shouldNotifyScannerSignal("DENIED")).toBe(false);
  });

  it("persists and delivers an outcome generated by the strategy engine", async () => {
    fetchMarketSeriesBatch.mockResolvedValue(new Map([
      ["EUR/USD", series("EUR/USD", "15min")],
      ["XAU/USD", series("XAU/USD", "15min")],
      ["GBP/USD", series("GBP/USD", "15min")],
      ["BTC/USD", series("BTC/USD", "15min")],
    ]));
    auditWithLLM.mockResolvedValue({
      verdict: "APPROVED",
      confidence: 82,
      adjustments: "Generated from aligned strategy evidence",
      asset: "EUR/USD",
      timeframe: "15MIN",
      direction: "SELL",
      entry: 3,
      stopLoss: 3.1,
      takeProfit: 2.8,
      ruleEvidence: ["Rules", "Rules", "Rules"],
      ruleFindings: [
        { title: "Rules", stance: "SELL", weight: 5 },
        { title: "Rules", stance: "SELL", weight: 4 },
        { title: "Rules", stance: "SELL", weight: 3 },
      ],
    });
    insert.mockImplementation(() => [{ insertId: 42 }]);
    sendTelegramMessage.mockResolvedValue({ delivered: true, telegramMessageId: "7" });
    insert.mockClear();
    sendTelegramMessage.mockClear();
    recordTelegramDelivery.mockClear();

    const result = await scanUser(1);

    expect(result.created).toBe(8);
    expect(insert).toHaveBeenCalled();
    expect(sendTelegramMessage).toHaveBeenCalled();
    expect(recordTelegramDelivery).toHaveBeenCalled();
    expect(auditWithLLM).toHaveBeenCalled();
    const firstAudit = auditWithLLM.mock.calls[0][0];
    expect(firstAudit.market).toMatchObject({ interval: "15min", trend: "UP", values: expect.any(Array) });
    expect(firstAudit.tradeSignal).toContain("raw market data");
  });

  it("never persists or sends a candidate rejected by the strategy engine", async () => {
    fetchMarketSeriesBatch.mockResolvedValue(new Map([
      ["EUR/USD", series("EUR/USD", "15min")],
      ["XAU/USD", series("XAU/USD", "15min")],
      ["GBP/USD", series("GBP/USD", "15min")],
      ["BTC/USD", series("BTC/USD", "15min")],
    ]));
    auditWithLLM.mockResolvedValue({
      verdict: "DENIED",
      confidence: 40,
      adjustments: "Insufficient rule evidence",
      ruleEvidence: [],
      ruleFindings: [],
    });
    insert.mockClear();
    sendTelegramMessage.mockClear();
    recordTelegramDelivery.mockClear();

    const result = await scanUser(1);

    expect(result.created).toBe(0);
    expect(insert).not.toHaveBeenCalled();
    expect(sendTelegramMessage).not.toHaveBeenCalled();
    expect(recordTelegramDelivery).not.toHaveBeenCalled();
  });
});

describe("scanner unavailable-market behavior", () => {
  it("skips all assets without inserting signals when OHLCV polling fails", async () => {
    fetchMarketSeriesBatch.mockImplementation(async () => { throw new Error("Twelve Data quota exhausted"); });
    insert.mockClear();

    const result = await scanUser(1);

    expect(result.created).toBe(0);
    expect(result.tracked).toBe(0);
    expect(result.marketData).toBe("unavailable");
    expect(insert).not.toHaveBeenCalled();
  });
});
