import { describe, expect, it, vi } from "vitest";

const { fetchMarketSeriesBatch, generateScannerDecisions, sendTelegramMessage, recordTelegramDelivery, createStrategyDecision, getSettings, hasRecentStrategyDecision, updateStrategyEngineStatus, insert, db } = vi.hoisted(() => {
  const fetchMarketSeriesBatch = vi.fn(async () => { throw new Error("Twelve Data quota exhausted"); });
  const generateScannerDecisions = vi.fn();
  const createStrategyDecision = vi.fn(async (input: any) => ({ id: 99, ...input }));
  const getSettings = vi.fn(async () => ({ setupCooldownMinutes: 30 }));
  const hasRecentStrategyDecision = vi.fn(async () => false);
  const updateStrategyEngineStatus = vi.fn();
  const sendTelegramMessage = vi.fn();
  const recordTelegramDelivery = vi.fn();
  const insert = vi.fn();
  const select = vi.fn(() => ({
    from: vi.fn(() => ({
      where: vi.fn(async () => []),
    })),
  }));
  const db = { select, insert, update: vi.fn() };
  return { fetchMarketSeriesBatch, generateScannerDecisions, sendTelegramMessage, recordTelegramDelivery, createStrategyDecision, getSettings, hasRecentStrategyDecision, updateStrategyEngineStatus, insert, db };
});

vi.mock("./db", () => ({
  getDb: vi.fn(async () => db),
  listStrategyRules: vi.fn(async () => [{ id: 1, title: "Rules", content: "Use confirmation." }]),
  getAllRulesText: vi.fn(async () => "Use confirmation."),
  createStrategyDecision,
  getSettings,
  hasRecentStrategyDecision,
  updateStrategyEngineStatus,
  getRelevantRulesText: vi.fn(async () => "## Rules\nUse confirmation."),
  createStrategyRule: vi.fn(),
  recordTelegramDelivery,
}));

vi.mock("./integrations", () => ({
  fetchMarketSeriesBatch,
  fetchMarketSnapshot: vi.fn(),
  fetchStrategyRulesFromSupabase: vi.fn(async () => []),
  forensicAnalysis: vi.fn(),
  formatApprovedTelegramMessage: vi.fn(() => "approved"),
  formatAuditResult: vi.fn(() => "audit"),
  generateScannerDecisions,
  mirrorToSupabase: vi.fn(),
  sendTelegramMessage,
}));

import { scanUser, shouldNotifyScannerSignal } from "./scanner";

const series = (symbol: string, interval: "15min" | "1h") => ({
  symbol,
  interval,
  values: [{ close: "1" }, { close: "2" }, { close: "3" }],
  close: 3,
  trend: "UP" as const,
  fetchedAt: new Date().toISOString(),
});

const allSeries = () => new Map([
  ["EUR/USD", series("EUR/USD", "15min")],
  ["XAU/USD", series("XAU/USD", "15min")],
  ["GBP/USD", series("GBP/USD", "15min")],
  ["BTC/USD", series("BTC/USD", "15min")],
]);

describe("scanner approval gate", () => {
  it("allows only approved outcomes to reach the notification branch", () => {
    expect(shouldNotifyScannerSignal("APPROVED")).toBe(true);
    expect(shouldNotifyScannerSignal("DENIED")).toBe(false);
  });

  it("persists and delivers outcomes generated by the strategy engine", async () => {
    fetchMarketSeriesBatch.mockResolvedValue(allSeries());
    generateScannerDecisions.mockImplementation(async ({ candidates }: any) => candidates.map((candidate: any) => ({
      verdict: "APPROVED",
      confidence: 82,
      adjustments: "Generated from aligned strategy evidence",
      asset: candidate.asset,
      timeframe: candidate.timeframe,
      market: candidate.market,
      direction: "SELL",
      entry: 3,
      stopLoss: 3.1,
      takeProfit: 2.8,
      ruleEvidence: ["Rules", "Rules", "Rules"],
      ruleFindings: [
        { title: "Rules", stance: "SELL", weight: 5 },
        { title: "Rules", stance: "SELL", weight: 4 },
        { title: "Rules", stance: "SELL", weight: 3 },
      ],
    })));
    insert.mockImplementation(() => [{ insertId: 42 }]);
    sendTelegramMessage.mockResolvedValue({ delivered: true, telegramMessageId: "7" });
    insert.mockClear();
    sendTelegramMessage.mockClear();
    recordTelegramDelivery.mockClear();

    const result = await scanUser(1);

    expect(result.created).toBe(8);
    expect(insert).toHaveBeenCalled();
    expect(sendTelegramMessage).toHaveBeenCalled();
    expect(recordTelegramDelivery).toHaveBeenCalled();
    expect(createStrategyDecision).toHaveBeenCalled();
    expect(updateStrategyEngineStatus).toHaveBeenCalledWith(1, { status: "AVAILABLE" });
    expect(generateScannerDecisions).toHaveBeenCalledTimes(1);
    const firstBatch = generateScannerDecisions.mock.calls[0][0];
    expect(firstBatch.candidates[0].market).toMatchObject({ interval: "15min", trend: "UP", values: expect.any(Array) });
    expect(firstBatch.candidates[0].asset).toBe("EUR/USD");
  });

  it("forwards every retrieved raw snapshot without scanner-side trend or cooldown filtering", async () => {
    const raw = allSeries();
    raw.set("EUR/USD", { ...series("EUR/USD", "15min"), trend: "SIDEWAYS" as any });
    fetchMarketSeriesBatch.mockResolvedValue(raw);
    generateScannerDecisions.mockResolvedValue([]);
    generateScannerDecisions.mockClear();
    createStrategyDecision.mockClear();

    const result = await scanUser(1);

    expect(result.created).toBe(0);
    expect(generateScannerDecisions).toHaveBeenCalledTimes(1);
    const batch = generateScannerDecisions.mock.calls[0][0];
    expect(batch.candidates).toHaveLength(8);
    expect(batch.candidates.find((candidate: any) => candidate.asset === "EUR/USD" && candidate.timeframe === "15MIN").market.trend).toBe("SIDEWAYS");
    expect(createStrategyDecision).not.toHaveBeenCalled();
  });

  it("fails closed when the strategy engine is unavailable", async () => {
    fetchMarketSeriesBatch.mockResolvedValue(allSeries());
    generateScannerDecisions.mockRejectedValue(new Error("LLM usage exhausted"));
    insert.mockClear();
    sendTelegramMessage.mockClear();
    recordTelegramDelivery.mockClear();

    const result = await scanUser(1);

    expect(result.created).toBe(0);
    expect(result.marketData).toBe("available");
    expect(insert).not.toHaveBeenCalled();
    expect(sendTelegramMessage).not.toHaveBeenCalled();
    expect(recordTelegramDelivery).not.toHaveBeenCalled();
    expect(createStrategyDecision).toHaveBeenCalledWith(expect.objectContaining({ verdict: "UNAVAILABLE", decisionReason: expect.stringContaining("Strategy engine unavailable") }));
  });

  it("never persists or sends a candidate rejected by the strategy engine", async () => {
    fetchMarketSeriesBatch.mockResolvedValue(allSeries());
    generateScannerDecisions.mockResolvedValue([{ asset: "EUR/USD", timeframe: "15MIN", verdict: "DENIED", confidence: 40, adjustments: "Insufficient rule evidence", ruleEvidence: [], ruleFindings: [], market: series("EUR/USD", "15min") }]);
    insert.mockClear();
    sendTelegramMessage.mockClear();
    recordTelegramDelivery.mockClear();

    const result = await scanUser(1);

    expect(result.created).toBe(0);
    expect(sendTelegramMessage).not.toHaveBeenCalled();
    expect(recordTelegramDelivery).not.toHaveBeenCalled();
    expect(createStrategyDecision).toHaveBeenCalledWith(expect.objectContaining({ verdict: "DENIED", decisionReason: "Insufficient rule evidence" }));
  });
});

describe("scanner unavailable-market behavior", () => {
  it("skips all assets without inserting signals when OHLCV polling fails", async () => {
    fetchMarketSeriesBatch.mockImplementation(async () => { throw new Error("Twelve Data quota exhausted"); });
    insert.mockClear();

    const result = await scanUser(1);

    expect(result.created).toBe(0);
    expect(result.tracked).toBe(0);
    expect(result.marketData).toBe("unavailable");
    expect(insert).not.toHaveBeenCalled();
  });
});
